trigger:
- main

pool:
  name: 'Default'

steps:
# Step 1: Install JDK 1.8 automatically from the Azure DevOps tool cache
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '1.8'  # Version of JDK to install
    jdkArchitectureOption: 'x64'  # Architecture type (x64)
    jdkSourceOption: 'toolCache'  # Install from the Azure DevOps tool cache
    installationDirectory: $(Agent.ToolsDirectory)/jdk  # Installation directory

# Step 2: Build with Maven using the installed JDK 1.8
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'  # Use the installed JDK from the tool installer
    jdkVersionOption: '1.8'  # Specify the version of JDK to use (set to 1.8 for compatibility)
    jdkArchitectureOption: 'x64'  # Specify the architecture type (x64)
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
